Optional inputs
fal-ai/dbt-cloud-action pull request #15
Opened 2022-09-13 17:48 UTC by sgoley

Took a first pass at solving my own feature request: https://github.com/fal-ai/dbt-cloud-action/issues/14

Attempts to add the following new inputs to the action's request body to the dbt api: 
 * schema_override
 * target_name_override
 
 Source API docs here: https://docs.getdbt.com/dbt-cloud/api-v2#tag/Jobs/operation/triggerRun

2022-09-13 21:02 UTC, chamini2 requested changes
Thanks for contributing. What do you think if instead we just let the user set the whole object instead of adding each optional property to the optional inputs?

```yaml
      - uses: fal-ai/dbt-cloud-action@main
        id: dbt_cloud_run
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
          dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}
          trigger_run_body:
            cause: "My cause"
            schema_override: ${{ secrets.schema }}
```

And we would just have to have a default value for that object's `cause` property before sending the request.

2022-09-13 21:02 UTC, chamini2 commented on action.yml
> +     default: "staging"
I would *not* set a default value for these and let dbt handle that.

2022-09-14 18:25 UTC, goley-aveone commented on action.yml
> +     default: "staging"
By that you mean to drop the whole line, not just empty string right?

2022-09-14 18:26 UTC, sgoley commented on action.yml
> +     default: "staging"
By that you mean to remove the whole default line 27, not just empty string correct?

2022-09-14 18:28 UTC, sgoley commented
> Thanks for contributing. What do you think if instead we just let the user set the whole object instead of adding each optional property to the optional inputs?
> 
> ```yaml
>       - uses: fal-ai/dbt-cloud-action@main
>         id: dbt_cloud_run
>         with:
>           dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
>           dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
>           dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}
>           trigger_run_body:
>             cause: "My cause"
>             schema_override: ${{ secrets.schema }}
> ```
> 
> And we would just have to have a default value for that object's `cause` property before sending the request.

I would say the reason not to make the whole schema a single string in secrets is so that values can be set dynamically like this: 

https://gist.github.com/sgoley/af3e1f857251786afb1d739ada2e2a03#file-fmtdeploy-yml-L83

2022-09-14 18:39 UTC, sgoley commented
Actually realized today that to mirror the dbtcloud native intregation, we will also need include the `git_branch` param.

2022-09-20 20:42 UTC, closed without merging

2022-09-20 23:44 UTC, chamini2 commented
This is now supported, check [v4.0](https://github.com/fal-ai/dbt-cloud-action/releases/tag/v4.0) release for details.